language: node_js
node_js:
  - "12"
  - "10"
  - "8"
cache:
  yarn: true
after_install: npm install --global yarn
install:
  - yarn
script:
  - yarn lint
  - yarn test-coverage
after_script:
  - npm install --global codecov coveralls codacy-coverage
  - cat ./coverage/lcov.info | coveralls
  - cat ./coverage/lcov.info | codecov
  - cat ./coverage/lcov.info | codacy-coverage
